backend:
  name: github
  repo: AquiferGrowth/ag-website
  branch: main # Branch to update (optional; defaults to main)
  base_url: https://ag-website-oauth.divjot-6b1.workers.dev

media_folder: "public/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads" # The src attribute for uploaded media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Hero Image", name: "heroImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
